#!/bin/bash

echo "========================================="
echo "GitHub CLI Installation Instructions"
echo "========================================="
echo ""
echo "Run these commands one by one in your terminal:"
echo ""
echo "# 1. Add the GitHub CLI repository"
echo "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo ""
echo "# 2. Add the repository to your sources"
echo 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null'
echo ""
echo "# 3. Update and install"
echo "sudo apt update"
echo "sudo apt install gh"
echo ""
echo "# 4. Authenticate with GitHub"
echo "gh auth login"
echo ""
echo "When prompted during 'gh auth login':"
echo "  - Choose: GitHub.com"
echo "  - Choose: HTTPS"
echo "  - Authenticate with: Login with a web browser (recommended)"
echo "  - Follow the browser prompts"
echo ""
echo "========================================="
echo "After installation, run: ./create-github-repo.sh"
echo "========================================="